### PR TITLE
Services, Repositories and Tests Additions

### PR DESCRIPTION
**Pull request by CodyWallbridge**
added functions to data services and repositories that will be needed for sprint 2, also added tests for those functions

### CODE REVIEW

**Comment by Speuce** [comment]
LGTM

**Review by noahc3 — APPROVED** [review]

**Comment by noahc3** [comment]
LOOKS GOOD TO ME!

**Comment by noahc3** [comment]
LETS GET THIS MERGED ‼️

**Comment by noahc3** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by noahc3** [comment]
LFGGGGG

**Review by noahc3 — APPROVED** [review]

**Review by noahc3 — APPROVED** [review]

**Review by nathanpoppe — APPROVED** [review]

**Pull request merged**
